url: http://dzfood.eu

# Site settings
title: 大众美食
email: feedback@dzfood.eu
description: "都灵大众美食官方网站"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: 毕业庆祝
  pic: 1
  position: Graduation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: 生日聚会
  pic: 2
  position: Birthday
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: 节日聚餐
  pic: 3
  position: Festival
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Corso Regina Margherita 152
  - line: 10152 Torino

# Build settings
markdown: kramdown
permalink: pretty
